package main

import (
	"bufio"
	"fmt"
	"io"
	"strings"
	"time"
)

// writer emits the migration as a single transaction. Either the whole mesh
// lands or none of it does — a half-loaded Beacon would compare against
// CoreScope and differ for reasons that have nothing to do with HopReach.
type writer struct {
	bw *bufio.Writer
}

func newWriter(w io.Writer) *writer {
	return &writer{bw: bufio.NewWriterSize(w, 1<<20)}
}

func (w *writer) flush() error { return w.bw.Flush() }

func (w *writer) printf(format string, args ...any) {
	fmt.Fprintf(w.bw, format, args...)
}

func (w *writer) header() {
	w.printf("-- Generated by cmd/corescope-to-beacon. Do not edit.\n")
	w.printf("BEGIN;\n\n")
}

func (w *writer) footer() {
	w.printf("\nCOMMIT;\n")
}

// hexLit renders bytes as a PostgreSQL bytea literal. Public keys arrive as
// hex strings and are stored as bytea, which is the one conversion this whole
// migration cannot get wrong: a mangled key silently becomes a different node.
func hexLit(hexStr string) string {
	s := strings.ToLower(strings.TrimSpace(hexStr))
	if len(s)%2 == 1 {
		s = "0" + s
	}
	return "'\\x" + s + "'::bytea"
}

func quote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "''") + "'"
}

// nullableText renders "" as SQL NULL. Beacon distinguishes an unset name
// from an empty one, and so should this.
func nullableText(s string) string {
	if s == "" {
		return "NULL"
	}
	return quote(s)
}

func nullableFloat(v *float64) string {
	if v == nil {
		return "NULL"
	}
	return fmt.Sprintf("%v", *v)
}

// tsOrNow renders a timestamp, falling back to now() for the zero value.
//
// Used only for columns Beacon declares NOT NULL. Anywhere the column is
// nullable, "never heard" stays NULL — see tsOrNull — because collapsing that
// to a real instant is what makes a silent node look active.
func tsOrNow(t time.Time) string {
	if t.IsZero() {
		return "now()"
	}
	return quote(t.UTC().Format(time.RFC3339))
}

func tsOrNull(t time.Time) string {
	if t.IsZero() {
		return "NULL"
	}
	return quote(t.UTC().Format(time.RFC3339))
}
